version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/cgpt
    goos:
      - linux
      - windows
      - darwin

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: cgpt
    homepage: https://github.com/tmc/cgpt
    description: A simple command line tool for working with LLMs.
    repository:
      owner: tmc
      name: homebrew-tap
      branch: "{{.ProjectName}}-{{.Version}}"
    commit_author:
      name: github-actions
      email: 41898282+github-actions[bot]@users.noreply.github.com
    custom_block: |
      head do
        url "https://github.com/tmc/cgpt.git"
        depends_on "pkg-config" => :build
      end

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
